# Generated by Django 2.1.2 on 2018-10-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallEndStart',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, null=True)),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallStartRecord',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('call_id', models.CharField(max_length=50, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('destination', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
