# Generated by Django 2.1.2 on 2018-10-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biller_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallEndStart',
            new_name='CallEndRecord',
        ),
    ]
