# Generated by Django 2.1.2 on 2018-10-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biller_app', '0003_auto_20181016_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('call_id', models.CharField(max_length=10)),
                ('dt_start', models.DateTimeField()),
                ('dt_end', models.DateTimeField()),
                ('duration', models.CharField(max_length=50)),
                ('closed_period_month', models.CharField(max_length=5)),
                ('closed_period_year', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=10)),
                ('total_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='callendrecord',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callstartrecord',
            name='destination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='callstartrecord',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
