# Generated by Django 2.1.2 on 2018-10-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biller_app', '0004_auto_20181022_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callendrecord',
            name='timestamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='callstartrecord',
            name='timestamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
