# Generated by Django 2.1.2 on 2018-10-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biller_app', '0005_auto_20181022_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callpair',
            name='call_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
