# Generated by Django 2.1.2 on 2018-10-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biller_app', '0006_auto_20181022_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callpair',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
