# Generated by Django 2.1.2 on 2018-10-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biller_app', '0007_auto_20181024_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callpair',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
